### ISSUE TITLE
clicking on autocomplete scrollbar closes window

### ISSUE THREAD

**Issue by dpouliot** [filamentgroup/auto-complete#12]
when the autocomplete results are too long, a scrollbar appears so the user can scroll through them, but clicking the scrollbar closes the window.

**Comment by dpouliot** [comment]
My fix is certainly a hack, but here is what I did to get it working for me...

``` javascript
 AutoComplete.prototype.select = function() {
    var selectedCount =$(this.menu.element).find(".menu-selected").length;
    if(selectedCount){//only close menu if a selection was made (clicks on scrollbar should not close menu)
      this.val( this.strip(this.menu.selectActive() || "") );
    }
  };
```

and in menu-all.js, menu.prototype.init:

``` javascript
        $( document ).bind( "mouseup", function(){
            //if an autocomplete menu, and user clicks in scrollbar, don't close
            if(self.element.classList[0] =="suggest" && $(self.element).find(".menu-selected").length == 0 && $(event.target).selector.tagName =="OL"){
                return false;
            }
            self.close();
        } );
```

**Comment by maggiewachs** [comment]
@dpouliot Thanks for the update! Would you mind adding that to a  PR so we can review?

**Comment by dpouliot** [comment]
I'm zeroing in on a better fix to this, one that only edits autocomplete.js, not menu-all.js. Trying to update line 389 as follows:

``` js
menu.$element.on( "mouseup",
        function() {
          var isScrolling = (this.classList[0] == "suggest" && $(this).find(".menu-selected").length == 0 && $(event.target).selector.tagName == "OL") ? true : false;
          if(isScrolling){
            return false;
          }else{
            $.proxy(autocomplete.select, autocomplete)
          }
        }
      );
```

The above code _almost_ works. Can you explain why this works:

``` js
menu.$element.on( "mouseup",  $.proxy(autocomplete.select, autocomplete)  );
```

but this doesn't work:

``` js
menu.$element.on( "mouseup", function() { $.proxy(autocomplete.select, autocomplete) } );
```

once i can call autocomplete from inside a function I think this will be fixed.

**Comment by maggiewachs** [comment]
@dpouliot `proxy` returns a function (in this case, the first argument `autocomplete.select`) with a new context (`autocomplete`), so the second example is unnecessarily enclosing `autocomplete.select` in an anonymous function. 

OK, on second look, I think the problem here is with the menu plugin, not autocomplete. Autocomplete uses menu to open/close the list of suggestions, and menu indiscriminately binds a click event to the `document` to close: https://github.com/filamentgroup/Menu/blob/master/src/menu.js#L182. 

Looks like the scrollbar is treated as part of the `document`, not the menu, so clicking on it closes the menu. You can see it happening on the [menu demo page](http://filamentgroup.github.io/Menu/examples/) if you inspect the menu and add a height value and `overflow: auto`:
![image](https://cloud.githubusercontent.com/assets/228885/19039420/d6fcf5ae-894d-11e6-9846-92aeca88865a.png)

We may need to make the menu close fn conditional so that it applies only to menu items and to specific elements outside of the menu (not the whole doc). Another thing we've done which works well is to add an invisible layer/div between the menu and the page so it _looks like_ you're clicking anywhere on the document to close, but in fact you're clicking on the div -- that may require some markup trickery, though, depending on where the autocomplete menu sits in the source.

So, my questions for you: 
- can you post a demo page for us to see?
- how long is the list of suggestions returned for the autocomplete you're testing? (wondering if there isn't a design solution here, just to rule it out)

cc @johnbender

**Comment by dpouliot** [comment]
http://master.origin.lm-esales.fgview.com/docs/components/forms-autocomplete.html
try clicking the scrollbar in that example. I think we are looking at 100+ items.

**Comment by dpouliot** [comment]
my first commit/pr included edits to menu-all.js, but it seemed hacky to me.

``` javascript
$( document ).bind( "mouseup", function(){
    //if an autocomplete menu, and user clicks in scrollbar, don't close
    if(self.element.classList[0] =="suggest" && $(self.element).find(".menu-selected").length == 0 && $(event.target).selector.tagName =="OL"){
        return false;
    }
    self.close();   
} );
```

**Comment by johnbender** [comment]
@dpouliot @maggiewachs 

@scottjehl pointed out that clicks won't fire on non-focusable elements (e.g. `body`) on iOS. So we'll have to go with some element checking in the binding. I'm going to update my PR and hopefully we'll get this sort out tomorrow.

**Comment by dpouliot** [comment]
fwiw, when I tested on my iphone, it seemed to work

**Comment by johnbender** [comment]
@dpouliot 

You can test my fix by using `filamentgroup/auto-complete#12` in your package.json.

**Comment by dpouliot** [comment]
we don't reference it in package.json, so I manually applied your edits to autocomplete and menu, and tested in chrome and ios safari and it worked in both.

**Comment by dpouliot** [comment]
@johnbender sorry I haven't looked at this in a while. I don't see PR #12. Has this fix been released?

**Comment by johnbender** [comment]
https://github.com/filamentgroup/auto-complete/pull/17

That's the PR. Hasn't been merged yet though. The fix is in branch '12'
which you can reference in the project deps directly if needs be.

**Comment by johnbender** [comment]
Ah just recalled that you don't pull it in that way. OK we need to merge
this I think? If I recall correctly there may have been some objections
internally.

**Comment by dpouliot** [comment]
Hi John, I deleted my comment when I found the PR. My issue is I'm responsible for our pattern library, which vets this, but not the application itself. the application pulls it in via package.json, but the PL just has assets/js/lib/autocomplete.js (0.2.3). The application team won't want to update the package.json with reference a PR for obvious reasons. But I think I can test it in our PL by replacing my autocomplete.js with `auto-complete/blob/12/src/core.js`, yes?

**Comment by johnbender** [comment]
https://github.com/filamentgroup/auto-complete/pull/17/files

Looks like the PR is purely a menu component update.

**Comment by dpouliot** [comment]
ok.... that's what happens when I wait so long, I forget! I see menu-all.js in my js/lib, I'll test there. The same holds true with this though, our application pulls in your node module, and they will be averse to pointing to a branch. I understand the reservations with this issue, the fix seemed inelegant.

**Comment by johnbender** [comment]
I think the Menu fix actually should be merged. I switched back from the
click to the mouseover per Scott's recommendation. I'll check in with them
on this.
