### ISSUE TITLE
Small delay on ajax request send

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/auto-complete#9]
If I type `crew` really fast, it makes the following requests, one for each keystroke:
![image](https://cloud.githubusercontent.com/assets/39355/12102261/4b2f341c-b2ff-11e5-85a2-fd852b7184cf.png)

**Comment by johnbender** [comment]
@zachleat 

We could let the stack unwind per keystroke by doing a `setTimeout` on the `fetch` call and including the `_fetchId` value as a param. Then we can check the `_requestId` before actually making the ajax call to see if the ids match. If the id has since changed then we can ignore the request. 

I'm curious if this is related to #10
